### PR TITLE
Add TAF1 X-linked dystonia-parkinsonism (XDP)

### PR DESCRIPTION
**Pull request by hdashnow**
I couldn't get more specific than a ~2000bp region. May be novel? Would be nice to narrow it down further.

### CODE REVIEW

**Comment by hdashnow** [comment]
@laurelhiatt would you be willing to take a look at this before merging?

**Comment by laurelhiatt** [comment]
sure! any specific aspects?

**Comment by hdashnow** [comment]
Confirm it it is a pathogenic tandem repeat and see if there is any way of
narrowing down the position. No rush!

**Comment by hdashnow** [comment]
Closing for now since the format has changed. Will move to Discussion and suggest doing a new PR in the future.
#17

**Pull request closed without merging**
